### ISSUE TITLE
meshio

### ISSUE THREAD

**Issue by nschloe** [truongd8593/gmsh-to-vtk-and-tecplot#1]
There's VTK and MSH support in [meshio](https://github.com/nschloe/meshio), so you perhaps only need the tecplot part here.

**Comment by trgdang** [comment]
Does [meshio](https://github.com/nschloe/meshio) support unstructured **quadrilateral** mesh?

**Comment by nschloe** [comment]
Yes, of course. meshio supports all cell types supported by the individual mesh format. See https://github.com/nschloe/meshio/blob/master/meshio/vtk_io.py#L60 for an overview of supported cells for VTK, for example.

**Comment by trgdang** [comment]
Cool. I shall focus on tecplot mesh exporter asap.
